import { DashboardOutlined } from "@ant-design/icons";
import { APP_PREFIX_PATH } from "configs/AppConfig";

const dashBoardNavTree = [
  {
    key: "main",
    path: `${APP_PREFIX_PATH}/main`,
    title: "Основные",
    icon: DashboardOutlined,
    breadcrumb: false,
    submenu: [
      {
        key: "catalog",
        path: `${APP_PREFIX_PATH}/main/catalog`,
        title: "Каталог",
        icon: DashboardOutlined,
        breadcrumb: true,
        submenu: [
          {
            key: "products",
            path: `${APP_PREFIX_PATH}/main/catalog/products`,
            title: "Товары",
            icon: DashboardOutlined,
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "categories",
            path: `${APP_PREFIX_PATH}/main/catalog/categories`,
            title: "Категории",
            icon: DashboardOutlined,
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "collections",
            path: `${APP_PREFIX_PATH}/main/catalog/collections`,
            title: "Коллекции",
            icon: DashboardOutlined,
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "combos",
            path: `${APP_PREFIX_PATH}/main/catalog/combos`,
            title: "Комбо",
            icon: DashboardOutlined,
            breadcrumb: true,
            submenu: [],
          },
        ],
      },
      {
        key: "planner",
        path: `${APP_PREFIX_PATH}/main/planner`,
        title: "Планировщик",
        icon: DashboardOutlined,
        breadcrumb: true,
        submenu: [],
      },
      {
        key: "orders",
        path: `${APP_PREFIX_PATH}/main/orders`,
        title: "Заказы",
        icon: DashboardOutlined,
        breadcrumb: true,
        submenu: [],
      },
      {
        key: "clients",
        path: `${APP_PREFIX_PATH}/main/clients`,
        title: "Клиенты",
        icon: DashboardOutlined,
        breadcrumb: true,
        submenu: [
          {
            key: "list",
            path: `${APP_PREFIX_PATH}/main/clients/list`,
            title: "Список клиентов",
            icon: DashboardOutlined,
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "groups",
            path: `${APP_PREFIX_PATH}/main/clients/groups`,
            title: "Группы клиентов",
            icon: DashboardOutlined,
            breadcrumb: true,
            submenu: [],
          },
        ],
      },
      {
        key: "banners",
        path: `${APP_PREFIX_PATH}/main/banners`,
        title: "Баннеры",
        icon: DashboardOutlined,
        breadcrumb: true,
        submenu: [],
      },
      {
        key: "promo-codes",
        path: `${APP_PREFIX_PATH}/main/promo-codes`,
        title: "Промокоды",
        icon: DashboardOutlined,
        breadcrumb: true,
        submenu: [],
      },
      {
        key: "offline-points",
        path: `${APP_PREFIX_PATH}/main/offline-points`,
        title: "Оффлайн точки",
        icon: DashboardOutlined,
        breadcrumb: true,
        submenu: [
          {
            key: "addresses",
            path: `${APP_PREFIX_PATH}/main/offline-points/addresses`,
            title: "Адреса",
            icon: DashboardOutlined,
            breadcrumb: true,
            submenu: [],
          },
          {
            key: "geo-zones",
            path: `${APP_PREFIX_PATH}/main/offline-points/geo-zones`,
            title: "Гео зоны",
            icon: DashboardOutlined,
            breadcrumb: true,
            submenu: [],
          },
        ],
      },
      {
        key: "employees",
        path: `${APP_PREFIX_PATH}/main/employees`,
        title: "Сотрудники",
        icon: DashboardOutlined,
        breadcrumb: true,
        submenu: [],
      },
      {
        key: "mailing",
        path: `${APP_PREFIX_PATH}/main/mailing`,
        title: "Рассылки",
        icon: DashboardOutlined,
        breadcrumb: true,
        submenu: [],
      },
    ],
  },
  {
    key: "system",
    path: `${APP_PREFIX_PATH}/system`,
    title: "Системные",
    icon: DashboardOutlined,
    breadcrumb: true,
    submenu: [
      {
        key: "settings",
        path: `${APP_PREFIX_PATH}/system/settings`,
        title: "Настройки",
        icon: DashboardOutlined,
        breadcrumb: true,
        submenu: [],
      },
      {
        key: "mobile-app",
        path: `${APP_PREFIX_PATH}/system/mobile-app`,
        title: "Мобильное приложение",
        icon: DashboardOutlined,
        breadcrumb: true,
        submenu: [],
      },
      {
        key: "logs",
        path: `${APP_PREFIX_PATH}/system/logs`,
        title: "Логи",
        icon: DashboardOutlined,
        breadcrumb: true,
        submenu: [],
      },
    ],
  },
];

const navigationConfig = [...dashBoardNavTree];

export default navigationConfig;
